[tool.poetry]
name = "cw-6-1"
version = "0.1.0"
description = ""
authors = ["finka759"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
